language: node_js
node_js:
- node
install:
- yarn install && yarn global add codecov
script:
- yarn test && codecov
deploy:
  provider: npm
  email: npmnijk@gmail.com
  api_key:
    secure: baXvvqVzItVfDvdlAs4/GBMP+yEMFsBTXA+5uDkjf/17O/SSCYIiEAB+j6K2cLkBR0DQlqK8GqBhNEeMibRoUNpVZ5pvEOv51H9OUv2saCOhquoEDjm+v7Zddp6Lx+4FNvSUAS7HbiNdWdjhPR5Y9hXAEpYxu4foJiQ/KaFx2OOemZrgFr78mwPlUpvmCL8+Mxky22Uwtkp3hGrdD21ORyB/FMs4jw8BJ9thZHUroltzDuHcUg72DQDtcablKfwyJCq4dxTJD5cdfUMpzef52BkUaZ/ZUc7FDw/KqyUfk4E8LcuVwCXSCo+62az5qjqvU2tdyDDK5Df0chyAi+t/MpUmBkebRrfaxXKCyusA8kEMf83/r80Y4b3KL4JOjVsgL1HMaGhVS9QTxRatg/mhqND9qja0N84vI0977+GKfwIekStomfHztLkfXQMxw6CgPFsqxI6z2VbwR7jLOUx18kO3pz3ugTY/0GZ6af+G9visCUrHrkKXIBnm5+TPSmHzIr0UxMdR1MKAkAJvEEWjxlZLEGle2bZL4sOkGoKRZMtcpXBF2ju07lJsD+2/TAAghHCxGxF2pem6GNeKFHP8h7Hu9+4PkHl1M7rnZZ2XXr+IDAi9H5C1FvW97+Afcqw3camkVRuf0fkjL3XQBv5G4pDuapDFibEqMCniaXBxzB8=
  on:
    branch: master
    tags: true
    repo: nijk/react-duration-input-mask
  skip_cleanup: true
